# Generated by Django 3.0.5 on 2020-06-10 10:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileIfo',
            new_name='UserProfileInfo',
        ),
    ]
